# Generated by Django 4.2.21 on 2025-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('task_desc', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=30)),
                ('assigned_on', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
